language: haskell
dist: trusty
ghc:
  - 7.0
  - 7.4
  - 7.6
  - 7.8
  - 8.0
script:
  - cabal configure && cabal build
# See https://github.com/mgsloan/th-reify-many/issues/8
allow-failures:
  - ghc: 7.0
  - ghc: 7.4
  - ghc: 7.6
